# USERS
CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
# CHARACTERS / MONSTERS
CREATE TABLE characters (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    hp SMALLINT UNSIGNED NOT NULL,
    ac SMALLINT UNSIGNED NOT NULL,
    current_hp SMALLINT UNSIGNED NOT NULL,
    image_url VARCHAR(255) NULL,

    FOREIGN KEY (user_id) REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE monsters (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    hp SMALLINT UNSIGNED NOT NULL,
    current_hp SMALLINT UNSIGNED NOT NULL,
    image_url VARCHAR(255) NULL,

    FOREIGN KEY (user_id) REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

# ENCOUNTERS
CREATE TABLE encounters (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dm_id INT UNSIGNED NOT NULL,
    code CHAR(5) NOT NULL UNIQUE,
    current INT UNSIGNED NULL,

    FOREIGN KEY (dm_id) REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE tokens (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    enc_id INT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NULL,
    x INT NOT NULL,
    y INT NOT NULL,
    initiative SMALLINT UNSIGNED NOT NULL,

    FOREIGN KEY (enc_id) REFERENCES encounters(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;